version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
  - package-ecosystem: gradle
    directory: android
    schedule:
      interval: daily
    allow:
      - dependency-name: 'com.auth0.android:auth0'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
