import type { PasswordlessChallenge, TokenType, MfaFactorType } from './common';

/** A base interface for API calls that allow passing custom headers.
 * @hidden
 */
interface RequestOptions {
  /** Optional custom headers to be included in the request. */
  headers?: Record<string, string>;
  [key: string]: any;
}

// ========= URL Builder Parameters =========

/** Parameters for building a URL for the `/authorize` endpoint. */
export interface AuthorizeUrlParameters extends RequestOptions {
  responseType: string;
  redirectUri: string;
  state: string;
}

/** Parameters for building a URL for the `/v2/logout` endpoint. */
export interface LogoutUrlParameters extends RequestOptions {
  federated?: boolean;
  clientId?: string;
  returnTo?: string;
}

// ========= Web Authorize & Logout Parameters =========

/**
 * Parameters for the web-based authorization flow.
 * @see https://auth0.com/docs/api/authentication#authorize-client
 */
export interface WebAuthorizeParameters {
  /**
   * Random string to prevent CSRF attacks.
   */
  state?: string;
  /**
   * One-time random value that is used to prevent replay attacks.
   */
  nonce?: string;
  /**
   * The intended API identifier that will be the consumer for the issued access token.
   */
  audience?: string;
  /**
   * The scopes requested for the issued tokens. e.g. `openid profile`
   */
  scope?: string;
  /**
   * The database connection in which to look for users.
   */
  connection?: string;
  /**
   * The maximum age in seconds that the resulting ID token should be issued for.
   */
  maxAge?: number;
  /**
   * The organization in which user's should be authenticated into.
   */
  organization?: string;
  /**
   * The invitation URL for those users who have been invited to join a specific organization.
   */
  invitationUrl?: string;
  /**
   * Specify a custom redirect URL to be used. Normally, you wouldn't need to call this method manually as the default value is autogenerated for you.
   *
   * If you are using this, ensure a proper redirect URL is constructed in the following format
   * - **Android:** `{YOUR_APP_PACKAGE_NAME}.auth0://{AUTH0_DOMAIN}/android/{YOUR_APP_PACKAGE_NAME}/callback`
   * - **iOS:** `{PRODUCT_BUNDLE_IDENTIFIER}.auth0://{AUTH0_DOMAIN}/ios/{PRODUCT_BUNDLE_IDENTIFIER}/callback`
   *
   * If you have `useLegacyCallbackUrl` set to true then the redirect URL should in the format
   * - **Android:** `{YOUR_APP_PACKAGE_NAME}://{AUTH0_DOMAIN}/android/{YOUR_APP_PACKAGE_NAME}/callback`
   * - **iOS:** `{PRODUCT_BUNDLE_IDENTIFIER}://{AUTH0_DOMAIN}/ios/{PRODUCT_BUNDLE_IDENTIFIER}/callback`
   */
  redirectUrl?: string;
  /**
   * Any additional arbitrary parameters to send along in the URL.
   */
  additionalParameters?: { [key: string]: string };
}

/**
 * Parameters for clearing the user's session.
 * @see https://auth0.com/docs/api/authentication#logout
 */
export interface ClearSessionParameters {
  /**
   * If `true`, the user will also be logged out from their identity provider (e.g., Google).
   * @default false
   */
  federated?: boolean;
  /** The URL to which the user is redirected after logout. */
  returnToUrl?: string;
}

// ========= OAuth/OIDC Token Flow Parameters =========

/** Parameters for exchanging a code for tokens (PKCE Flow). */
export interface ExchangeParameters extends RequestOptions {
  code: string;
  verifier: string;
  redirectUri: string;
}

/**
 * Parameters for exchanging a refresh token for session transfer credentials (Native to Web SSO).
 * This allows apps that manage their own tokens to obtain a session transfer token
 * without using the Credentials Manager.
 *
 * @see https://auth0.com/docs/authenticate/single-sign-on/native-to-web/configure-implement-native-to-web
 */
export interface SSOExchangeParameters extends RequestOptions {
  /**
   * The refresh token to exchange for a session transfer token.
   */
  refreshToken: string;
}

/** Parameters for exchanging a native social provider's token for Auth0 tokens. */
export interface ExchangeNativeSocialParameters extends RequestOptions {
  subjectToken: string;
  subjectTokenType: string;
  userProfile?: string;
  audience?: string;
  scope?: string;
}

/**
 * Parameters for Custom Token Exchange (RFC 8693).
 * Exchanges an external identity provider token for Auth0 tokens.
 *
 * Custom Token Exchange allows you to exchange tokens from external identity
 * providers for Auth0 tokens. The external token must be validated in Auth0
 * Actions using cryptographic verification.
 *
 * @see https://auth0.com/docs/authenticate/custom-token-exchange
 */
export interface CustomTokenExchangeParameters {
  /**
   * The external token to be exchanged for Auth0 tokens.
   * Must be validated in Auth0 Actions using cryptographic verification.
   */
  subjectToken: string;

  /**
   * The type identifier for the subject token being exchanged.
   *
   * Must be a unique profile token type URI starting with `https://` or `urn:`.
   *
   * Valid patterns:
   * - `urn:yourcompany:token-type` - Company-specific URN (recommended)
   * - `https://yourcompany.com/tokens/custom` - HTTPS URL under your control
   *
   * Reserved namespaces (forbidden):
   * - `http://auth0.com/*`, `https://auth0.com/*`
   * - `http://okta.com/*`, `https://okta.com/*`
   * - `urn:ietf:*`, `urn:auth0:*`, `urn:okta:*`
   *
   * @example "urn:acme:legacy-system-token" // Custom legacy token
   * @example "https://yourcompany.com/tokens/partner-jwt" // Custom HTTPS identifier
   */
  subjectTokenType: string;

  /**
   * The target audience for the requested Auth0 token.
   * Must match an API identifier configured in your Auth0 tenant.
   */
  audience?: string;

  /**
   * Space-separated list of OAuth 2.0 scopes.
   * @default "openid profile email"
   */
  scope?: string;

  /**
   * Organization ID or name for authenticating in an organization context.
   * When provided, the organization ID will be present in the access token.
   */
  organization?: string;
}

/**
 * Parameters for authenticating with a username and password.
 * @see https://auth0.com/docs/api-auth/grant/password
 */
export interface PasswordRealmParameters extends RequestOptions {
  username: string;
  password: string;
  realm: string;
  audience?: string;
  scope?: string;
}

/**
 * Parameters for refreshing an access token.
 * @see https://auth0.com/docs/tokens/refresh-tokens
 */
export interface RefreshTokenParameters extends RequestOptions {
  /**
   * The issued refresh token
   */
  refreshToken: string;
  /**
   * The scopes requested for the issued tokens. e.g. `openid profile`
   */
  scope?: string;
  /**
   * The intended API identifier that will be the consumer for the issued access token.
   */
  audience?: string;
}

/** Parameters for revoking a refresh token. */
export interface RevokeOptions extends RequestOptions {
  refreshToken: string;
}

// ========= Passwordless Flow Parameters =========

/** Parameters for initiating passwordless login with an email. */
export interface PasswordlessEmailParameters extends RequestOptions {
  email: string;
  send?: 'link' | 'code';
  authParams?: object;
}

/** Parameters for initiating passwordless login with SMS. */
export interface PasswordlessSmsParameters extends RequestOptions {
  phoneNumber: string;
  send?: 'link' | 'code';
  authParams?: object;
}

/** Parameters for completing passwordless login with an email code/OTP. */
export interface LoginEmailParameters extends RequestOptions {
  email: string;
  code: string;
  audience?: string;
  scope?: string;
}

/** Parameters for completing passwordless login with an SMS code/OTP. */
export interface LoginSmsParameters extends RequestOptions {
  phoneNumber: string;
  code: string;
  audience?: string;
  scope?: string;
}

// ========= Multi-Factor Authentication (MFA) Parameters =========

/** Parameters for logging in with an OTP code after an MFA challenge. */
export interface LoginOtpParameters extends RequestOptions {
  mfaToken: string;
  otp: string;
  audience?: string;
}

/** Parameters for logging in with an Out-of-Band (OOB) code after an MFA challenge. */
export interface LoginOobParameters extends RequestOptions {
  mfaToken: string;
  oobCode: string;
  bindingCode?: string;
}

/** Parameters for logging in with a recovery code after an MFA challenge. */
export interface LoginRecoveryCodeParameters extends RequestOptions {
  mfaToken: string;
  recoveryCode: string;
}

/** Parameters for requesting an MFA challenge. */
export interface MfaChallengeParameters extends RequestOptions {
  mfaToken: string;
  challengeType?: 'oob' | 'otp';
  authenticatorId?: string;
}

// ========= MFA Flexible Factors Grant Parameters =========

/** Parameters for listing enrolled MFA authenticators. */
export interface MfaGetAuthenticatorsParameters {
  mfaToken: string;
  /**
   * Restrict the returned authenticators to the given factor types. Use the
   * {@link MfaFactorType} constants as the single, platform-agnostic vocabulary;
   * each platform maps these to its native filtering tokens. Omit or pass an
   * empty array to return all enrolled authenticators (the SDK supplies the
   * full set of factor types on every platform).
   *
   * @remarks
   * - **Android** cannot isolate `push` — its effective channel is `auth0`,
   *   so a `push`-only filter may not match Guardian authenticators.
   * - **Android** cannot distinguish `sms` from `voice` when filtering — both
   *   resolve to the `phone` type, so filtering by either returns both channels.
   *   Inspect the {@link MfaAuthenticator.oobChannel} field to tell them apart.
   *   (iOS narrows phone-type results by `oobChannel` when only one of
   *   `sms`/`voice` is requested.)
   */
  factorsAllowed?: MfaFactorType[];
}

/**
 * Enroll an OTP (TOTP) authenticator.
 *
 * @example
 * ```ts
 * import { MfaFactorType } from 'react-native-auth0';
 * const result = await mfa.enroll({ mfaToken, factorType: MfaFactorType.OTP });
 * // result.secret, result.barcodeUri
 * ```
 */
export interface MfaEnrollOtpParameters {
  mfaToken: string;
  factorType: 'otp';
}

/**
 * Enroll an SMS MFA factor.
 * Requires a phone number in E.164 format.
 *
 * @example
 * ```ts
 * import { MfaFactorType } from 'react-native-auth0';
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.SMS, phoneNumber: '+12025550135' });
 * ```
 */
export interface MfaEnrollSmsParameters {
  mfaToken: string;
  factorType: 'sms';
  phoneNumber: string;
}

/**
 * Enroll a voice call MFA factor.
 * Requires a phone number in E.164 format.
 *
 * @remarks
 * Voice is only enrolled as a distinct factor on the **web** platform. On the
 * **native** platforms (iOS/Android), the underlying Auth0.swift and
 * Auth0.Android SDKs do not expose a voice OOB channel, so a voice request is
 * enrolled as **SMS** on the same phone number. Use {@link MfaEnrollSmsParameters}
 * directly on native if SMS is the intended factor.
 *
 * @example
 * ```ts
 * import { MfaFactorType } from 'react-native-auth0';
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.VOICE, phoneNumber: '+12025550135' });
 * ```
 */
export interface MfaEnrollVoiceParameters {
  mfaToken: string;
  factorType: 'voice';
  phoneNumber: string;
}

/**
 * Enroll an email MFA factor.
 *
 * @example
 * ```ts
 * import { MfaFactorType } from 'react-native-auth0';
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.EMAIL, email: 'user@example.com' });
 * ```
 */
export interface MfaEnrollEmailParameters {
  mfaToken: string;
  factorType: 'email';
  email: string;
}

/**
 * Enroll a push notification MFA factor (Auth0 Guardian).
 *
 * @example
 * ```ts
 * import { MfaFactorType } from 'react-native-auth0';
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.PUSH });
 * ```
 */
export interface MfaEnrollPushParameters {
  mfaToken: string;
  factorType: 'push';
}

/**
 * Union type for all MFA enrollment parameter types.
 * Each variant is discriminated by the `factorType` field.
 *
 * @example
 * ```ts
 * import { MfaFactorType } from 'react-native-auth0';
 *
 * // OTP
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.OTP });
 * // SMS
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.SMS, phoneNumber: '+1...' });
 * // Voice
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.VOICE, phoneNumber: '+1...' });
 * // Email
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.EMAIL, email: 'user@example.com' });
 * // Push
 * await mfa.enroll({ mfaToken, factorType: MfaFactorType.PUSH });
 * ```
 */
export type MfaEnrollParameters =
  | MfaEnrollOtpParameters
  | MfaEnrollSmsParameters
  | MfaEnrollVoiceParameters
  | MfaEnrollEmailParameters
  | MfaEnrollPushParameters;

/** Parameters for requesting an MFA challenge via the MFA API. */
export interface MfaChallengeWithAuthenticatorParameters {
  mfaToken: string;
  authenticatorId: string;
}

/** Parameters for verifying an MFA OTP code (authenticator app). */
export interface MfaVerifyOtpParameters {
  mfaToken: string;
  otp: string;
  /** Space-separated list of OAuth 2.0 scopes to request for the returned credentials. */
  scope?: string;
  /** API audience to request for the returned credentials. */
  audience?: string;
}

/** Parameters for verifying an MFA OOB code (SMS/Email/Push). */
export interface MfaVerifyOobParameters {
  mfaToken: string;
  oobCode: string;
  bindingCode?: string;
  /** Space-separated list of OAuth 2.0 scopes to request for the returned credentials. */
  scope?: string;
  /** API audience to request for the returned credentials. */
  audience?: string;
}

/** Parameters for verifying with a recovery code. */
export interface MfaVerifyRecoveryCodeParameters {
  mfaToken: string;
  recoveryCode: string;
  /** Space-separated list of OAuth 2.0 scopes to request for the returned credentials. */
  scope?: string;
  /** API audience to request for the returned credentials. */
  audience?: string;
}

/** Union type for all MFA verification parameter types. */
export type MfaVerifyParameters =
  | MfaVerifyOtpParameters
  | MfaVerifyOobParameters
  | MfaVerifyRecoveryCodeParameters;

// ========= User Management & Profile Parameters =========

/** Parameters for accessing the `/userinfo` endpoint. */
export interface UserInfoParameters extends RequestOptions {
  token: string;
  /**
   * The type of the token. When 'DPoP', DPoP headers will be generated automatically.
   * Defaults to the client's configured token type.
   */
  tokenType?: TokenType;
}

/** Parameters for requesting a password reset email. */
export interface ResetPasswordParameters extends RequestOptions {
  email: string;
  connection: string;
  organization?: string;
}

/** Parameters for creating a new user in a database connection. */
export interface CreateUserParameters extends RequestOptions {
  email: string;
  password: string;
  connection: string;
  username?: string;
  given_name?: string;
  family_name?: string;
  name?: string;
  nickname?: string;
  picture?: string;
  metadata?: object;
}

// ========= Passkey Parameters =========

/**
 * Parameters for requesting a passkey signup challenge from Auth0.
 *
 * The challenge response contains WebAuthn creation options that should
 * be passed to the platform's credential manager (CredentialManager on Android,
 * ASAuthorizationController on iOS) to create a new passkey credential.
 *
 * @see https://auth0.com/docs/authenticate/database-connections/passkeys
 */
export interface PasskeySignupChallengeParameters {
  /** The user's email address. */
  email?: string;
  /** The user's phone number. */
  phoneNumber?: string;
  /** The user's username. */
  username?: string;
  /** The user's display name. */
  name?: string;
  /** The user's first name. */
  givenName?: string;
  /** The user's last name. */
  familyName?: string;
  /** The user's preferred nickname. */
  nickname?: string;
  /** URL pointing to the user's profile picture. */
  picture?: string;
  /** Additional user metadata as key-value pairs. */
  userMetadata?: Record<string, string>;
  /** The database connection name. */
  realm?: string;
  /** Organization ID or name for authenticating in an organization context. */
  organization?: string;
}

/**
 * Parameters for requesting a passkey login challenge from Auth0.
 *
 * The challenge response contains WebAuthn request options that should
 * be passed to the platform's credential manager to assert an existing passkey.
 *
 * @see https://auth0.com/docs/authenticate/database-connections/passkeys
 */
export interface PasskeyLoginChallengeParameters {
  /** The database connection name. */
  realm?: string;
  /** Organization ID or name for authenticating in an organization context. */
  organization?: string;
}

/**
 * Response from a passkey signup challenge request.
 * Contains the auth session and WebAuthn creation options for the platform credential manager.
 */
export interface PasskeyChallengeResponse {
  /** The auth session identifier to be used in the subsequent exchange call. */
  authSession: string;
  /** The raw WebAuthn public key credential creation/request options as JSON. */
  authParamsPublicKey: Record<string, any>;
}

/**
 * Parameters for exchanging a passkey credential response for Auth0 tokens.
 *
 * After the platform credential manager returns the credential (either a new
 * registration or an assertion), pass the auth_session and the credential JSON
 * response to this method to obtain Auth0 tokens.
 *
 * @see https://auth0.com/docs/authenticate/database-connections/passkeys
 */
export interface GetTokenByPasskeyParameters {
  /** The auth session received from the challenge response. */
  authSession: string;
  /** The JSON string of the PublicKeyCredential response from the platform credential manager. */
  authResponse: string;
  /** The database connection name. */
  realm?: string;
  /** The target API identifier for the issued access token. */
  audience?: string;
  /**
   * Space-separated list of OAuth 2.0 scopes.
   * @default "openid profile email"
   */
  scope?: string;
  /** Organization ID or name for authenticating in an organization context. */
  organization?: string;
}

// ========= Passkey Enrollment Parameters =========

/**
 * Parameters for requesting a passkey enrollment challenge from the My Account API.
 *
 * Passkey enrollment adds a passkey to an already-authenticated user's account.
 * Requires an access token with audience `https://{domain}/me/v1` and
 * scope `create:me:authentication_methods`.
 *
 * @see https://auth0.com/docs/authenticate/database-connections/passkeys
 */
export interface PasskeyEnrollmentChallengeParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** Unique identifier of user's identity (for linked accounts). */
  userIdentity?: string;
  /** Database connection name. */
  connection?: string;
}

/**
 * Response from a passkey enrollment challenge request.
 * Contains the authentication method ID, auth session, and WebAuthn creation options.
 */
export interface PasskeyEnrollmentChallengeResponse {
  /** Authentication method ID (needed for the verify step). */
  authenticationMethodId: string;
  /** Auth session identifier for the verify step. */
  authSession: string;
  /** WebAuthn PublicKeyCredentialCreationOptions for the platform credential manager. */
  authParamsPublicKey: Record<string, any>;
}

/**
 * Parameters for verifying a passkey enrollment with the My Account API.
 *
 * After the platform credential manager returns the credential registration,
 * pass the auth session and the credential JSON response to this method
 * to complete the enrollment.
 */
export interface EnrollPasskeyParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** Authentication method ID from the challenge response. */
  authenticationMethodId: string;
  /** Auth session from the challenge response. */
  authSession: string;
  /** JSON string of the PublicKeyCredential response from the platform credential manager. */
  authResponse: string;
  /** The public key parameters from the enrollment challenge response. */
  authParamsPublicKey: Record<string, any>;
}

/**
 * Represents an enrolled passkey authentication method.
 * Returned after successful enrollment verification.
 */
export interface PasskeyAuthenticationMethod {
  /** Authentication method ID. */
  id: string;
  /** Type (always "passkey"). */
  type: string;
  /** User identity ID. */
  userIdentityId: string;
  /** User agent of the device used to enroll. */
  userAgent?: string;
  /** Credential key ID. */
  keyId: string;
  /** Public key (base64-encoded). */
  publicKey: string;
  /** User handle (base64url-encoded). */
  userHandle: string;
  /** Device type: "single_device" or "multi_device". */
  credentialDeviceType: string;
  /** Whether the credential is backed up. */
  credentialBackedUp: boolean;
  /** Creation timestamp (ISO 8601). */
  createdAt: string;
  /** Authenticator Attestation GUID. */
  aaguid: string;
  /** Relying party identifier. */
  relyingPartyId: string;
}

// ========= Passwordless OTP (Database Connections) =========

/**
 * Runtime constants for passwordless OTP delivery methods.
 *
 * `TEXT` sends the one-time code via SMS (the server default); `VOICE`
 * delivers it through a voice call.
 *
 * @example
 * ```typescript
 * import { DeliveryMethod } from 'react-native-auth0';
 *
 * await auth0.passwordless.challengeWithPhoneNumber({
 *   phoneNumber: '+15555550123',
 *   connection: 'Username-Password-Authentication',
 *   deliveryMethod: DeliveryMethod.VOICE,
 * });
 * ```
 */
export const DeliveryMethod = {
  TEXT: 'text',
  VOICE: 'voice',
} as const;

/**
 * Delivery method for a phone-number OTP challenge.
 *
 * Derived from {@link DeliveryMethod} so the union and the runtime constants
 * cannot drift apart.
 */
export type PasswordlessDeliveryMethod =
  (typeof DeliveryMethod)[keyof typeof DeliveryMethod];

/**
 * Parameters for issuing a passwordless OTP challenge to an email address.
 *
 * @remarks Native only (iOS, Android). Not supported on web.
 */
export interface PasswordlessChallengeEmailParameters {
  /** The email address to send the one-time code to. */
  email: string;
  /**
   * The name of the database connection; it must have `email_otp` enabled.
   */
  connection: string;
  /**
   * Whether to allow sign-up if the user does not yet exist.
   * @default false
   */
  allowSignup?: boolean;
}

/**
 * Parameters for issuing a passwordless OTP challenge to a phone number.
 *
 * @remarks Native only (iOS, Android). Not supported on web.
 */
export interface PasswordlessChallengePhoneParameters {
  /** The E.164 phone number to send the one-time code to (e.g. `"+15555550123"`). */
  phoneNumber: string;
  /**
   * The name of the database connection; it must have `phone_otp` enabled.
   */
  connection: string;
  /**
   * How to deliver the code, by SMS or voice call.
   * @default "text"
   */
  deliveryMethod?: PasswordlessDeliveryMethod;
  /**
   * Whether to allow sign-up if the user does not yet exist.
   * @default false
   */
  allowSignup?: boolean;
}

/**
 * Parameters for completing a passwordless OTP flow by verifying the code.
 *
 * @remarks Native only (iOS, Android). Not supported on web.
 */
export interface PasswordlessLoginOtpParameters {
  /** The challenge returned by a prior `challengeWithEmail`/`challengeWithPhoneNumber` call. */
  challenge: PasswordlessChallenge;
  /** The one-time code the user received via email, SMS, or voice call. */
  otp: string;
  /** The target API identifier for the issued access token. */
  audience?: string;
  /**
   * Space-separated list of OAuth 2.0 scopes.
   *
   * An empty string is treated the same as omitting the value and falls back
   * to the default. The `openid` scope is always included by the underlying SDK.
   * @default "openid profile email"
   */
  scope?: string;
}

// ========= My Account — Authentication Method Management =========

/**
 * Supported authentication method types for filtering.
 */
export type AuthenticationMethodType =
  | 'passkey'
  | 'phone'
  | 'email'
  | 'totp'
  | 'push-notification'
  | 'recovery-code'
  | 'webauthn-platform'
  | 'webauthn-roaming'
  | 'password';

/**
 * Runtime constants for authentication method types.
 *
 * @example
 * ```typescript
 * import { AuthenticationMethodTypes } from 'react-native-auth0';
 *
 * const methods = await myAccount.getAuthenticationMethods({
 *   accessToken,
 *   type: AuthenticationMethodTypes.PASSKEY,
 * });
 * ```
 */
export const AuthenticationMethodTypes = {
  PASSKEY: 'passkey',
  PHONE: 'phone',
  EMAIL: 'email',
  TOTP: 'totp',
  PUSH_NOTIFICATION: 'push-notification',
  RECOVERY_CODE: 'recovery-code',
  WEBAUTHN_PLATFORM: 'webauthn-platform',
  WEBAUTHN_ROAMING: 'webauthn-roaming',
  PASSWORD: 'password',
} as const;

/**
 * Runtime constants for preferred phone authentication methods.
 *
 * @example
 * ```typescript
 * import { PreferredAuthenticationMethods } from 'react-native-auth0';
 *
 * await myAccount.enrollPhone({
 *   accessToken,
 *   phoneNumber: '+1234567890',
 *   preferredAuthenticationMethod: PreferredAuthenticationMethods.SMS,
 * });
 * ```
 */
export const PreferredAuthenticationMethods = {
  SMS: 'sms',
  VOICE: 'voice',
} as const;

/**
 * Parameters for listing authentication methods from the My Account API.
 */
export interface GetAuthenticationMethodsParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** Optional type filter to retrieve only methods of a specific type. */
  type?: AuthenticationMethodType;
}

/**
 * Parameters for retrieving a single authentication method by ID.
 */
export interface GetAuthenticationMethodByIdParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** The ID of the authentication method to retrieve. */
  id: string;
}

/**
 * Parameters for updating an authentication method by ID.
 */
export interface UpdateAuthenticationMethodByIdParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** The ID of the authentication method to update. */
  id: string;
  /** The friendly name of the authentication method. */
  name?: string;
  /** The preferred communication method for phone authenticators. */
  preferredAuthenticationMethod?: 'sms' | 'voice';
}

/**
 * Parameters for deleting an authentication method by ID.
 */
export interface DeleteAuthenticationMethodByIdParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** The ID of the authentication method to delete. */
  id: string;
}

/**
 * Represents a generic authentication method returned by the My Account API.
 */
export interface AuthenticationMethod {
  /** Authentication method ID. */
  id: string;
  /** The type of authentication method (e.g., "passkey", "phone", "email", "totp"). */
  type: string;
  /** Creation timestamp (ISO 8601). */
  createdAt: string;
  /** Usage classification (e.g., "mfa", "first_factor"). */
  usage: string[];
  /** Whether the method has been confirmed/verified. */
  confirmed?: boolean;
  /** Friendly name of the authentication method. */
  name?: string;
  /** Credential key ID (passkey/webauthn). */
  keyId?: string;
  /** Public key (passkey/webauthn). */
  publicKey?: string;
  /** User handle (passkey). */
  userHandle?: string;
  /** Device type: "single_device" or "multi_device" (passkey). */
  credentialDeviceType?: string;
  /** Whether the credential is backed up (passkey). */
  credentialBackedUp?: boolean;
  /** User agent of the device used to enroll (passkey). */
  userAgent?: string;
  /** Authenticator Attestation GUID (passkey). */
  aaguid?: string;
  /** Relying party identifier (passkey/webauthn). */
  relyingPartyId?: string;
  /** User identity ID. */
  identityUserId?: string;
  /** Transports used by the authenticator (passkey). */
  transports?: string[];
  /** Phone number (phone method). */
  phoneNumber?: string;
  /** Preferred communication method (phone method). */
  preferredAuthenticationMethod?: string;
  /** Email address (email method). */
  email?: string;
  /** Date of last password reset (password method). */
  lastPasswordReset?: string;
}

// ========= My Account — Factor Enrollment Parameters =========

/**
 * Parameters for enrolling a phone number as an authentication method.
 * After enrollment, an OTP code will be sent to the phone number which must
 * be confirmed via `confirmPhoneEnrollment`.
 */
export interface EnrollPhoneParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** The phone number to enroll (E.164 format, e.g., "+1234567890"). */
  phoneNumber: string;
  /** The preferred communication method for sending OTP codes. */
  preferredAuthenticationMethod?: 'sms' | 'voice';
}

/**
 * Parameters for enrolling an email address as an authentication method.
 * After enrollment, an OTP code will be sent to the email which must
 * be confirmed via `confirmEmailEnrollment`.
 */
export interface EnrollEmailParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** The email address to enroll. */
  emailAddress: string;
}

/**
 * Parameters for enrolling a TOTP authenticator app.
 * Returns a QR code URI and optional manual input code.
 * Must be confirmed with an OTP code from the authenticator app via `confirmTOTPEnrollment`.
 */
export interface EnrollTOTPParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
}

/**
 * Parameters for enrolling push notification as an authentication method.
 * Returns a QR code URI for pairing with a push notification app.
 * Must be confirmed via `confirmPushNotificationEnrollment`.
 */
export interface EnrollPushNotificationParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
}

/**
 * Parameters for enrolling a recovery code as an authentication method.
 * Returns a recovery code that the user should store securely.
 * Must be confirmed via `confirmRecoveryCodeEnrollment`.
 */
export interface EnrollRecoveryCodeParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
}

/**
 * Parameters for confirming an enrollment that requires an OTP code.
 * Used for phone, email, and TOTP enrollments.
 */
export interface ConfirmOTPEnrollmentParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** The authentication method ID from the enrollment challenge response. */
  id: string;
  /** The auth session from the enrollment challenge response. */
  authSession: string;
  /** The one-time password code sent to the user or generated by the authenticator app. */
  otpCode: string;
}

/**
 * Parameters for confirming a recovery code enrollment.
 * Does not require an OTP code.
 */
export interface ConfirmRecoveryCodeEnrollmentParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** The authentication method ID from the enrollment challenge response. */
  id: string;
  /** The auth session from the enrollment challenge response. */
  authSession: string;
}

/**
 * Parameters for confirming a push notification enrollment.
 * Does not require an OTP code.
 */
export interface ConfirmPushNotificationEnrollmentParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
  /** The authentication method ID from the enrollment challenge response. */
  id: string;
  /** The auth session from the enrollment challenge response. */
  authSession: string;
}

/**
 * Parameters for retrieving available factors from the My Account API.
 */
export interface GetFactorsParameters {
  /** Access token with My Account API scopes. */
  accessToken: string;
}

// ========= My Account — Factor Enrollment Responses =========

/**
 * Response from a phone or email enrollment challenge.
 * Contains the authentication method ID and auth session needed for confirmation.
 */
export interface EnrollmentChallenge {
  /** The unique identifier for the authentication method. */
  id: string;
  /** The unique session identifier for the enrollment (needed for confirmation). */
  authSession: string;
}

/**
 * Response from a TOTP or push notification enrollment challenge.
 * Contains the QR code URI for pairing with an authenticator app.
 */
export interface TOTPEnrollmentChallenge {
  /** The unique identifier for the authentication method. */
  id: string;
  /** The unique session identifier for the enrollment (needed for confirmation). */
  authSession: string;
  /** The URI for the QR code to be scanned by the authenticator app. */
  barcodeUri: string;
  /** The manual input code as an alternative to scanning the QR code. */
  manualInputCode?: string;
}

/**
 * Response from a recovery code enrollment challenge.
 * Contains the recovery code that the user must store securely.
 */
export interface RecoveryCodeEnrollmentChallenge {
  /** The unique identifier for the authentication method. */
  id: string;
  /** The unique session identifier for the enrollment (needed for confirmation). */
  authSession: string;
  /** The recovery code value that the user should store securely. */
  recoveryCode: string;
}

/**
 * Represents an available authentication factor from the My Account API.
 */
export interface Factor {
  /** The authentication method type (e.g., "phone", "email", "totp", "push-notification", "recovery-code"). */
  type: string;
  /** Usage classification (e.g., ["mfa"], ["first_factor", "mfa"]). */
  usage?: string[];
}

// ========= User Management & Profile Parameters =========

/**
 * Parameters for patching a user's metadata via the Management API.
 * Requires an access token with `update:current_user_metadata` scope.
 */
export interface PatchUserParameters {
  /** The ID of the user to update (e.g., `auth0|12345`). */
  id: string;
  /** An object containing the metadata to set or update. */
  metadata: Record<string, any>;
}

/**
 * Parameters for retrieving a user's full profile from the Management API.
 * Requires an access token with `read:current_user` scope.
 */
export interface GetUserParameters {
  /** The ID of the user to retrieve. */
  id: string;
}
