name: Publish release to package manager

inputs:
  node-version:
    required: true
  npm-token:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Publish release to NPM
      run: yarn publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
