name: Create npm and GitHub Release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # For publishing to npm using --provenance
  pages: write # For publishing documentation

### TODO: Replace instances of './.github/workflows/' w/ `auth0/dx-sdk-actions/workflows/` and append `@latest` after the common `dx-sdk-actions` repo is made public.
### TODO: Also remove `get-prerelease`, `get-release-notes`, `get-version`, `npm-publish`, `release-create`, and `tag-exists` actions from this repo's .github/actions folder once the repo is public.
### TODO: Also remove `npm-release` workflow from this repo's .github/workflows folder once the repo is public.

jobs:
  rl-scanner:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn build

      - name: Create tgz build artifact
        run: |
          tar -czvf react-native-auth0.tgz *

      - name: Get version
        id: get_version
        run: |
          version=$(head -1 .version)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Run RL Scanner
        uses: auth0/devsecops-tooling/.github/actions/rl-scan@e29f26478db18ff0bcbe4bc447a8fbd54fbeec9e # main on 2026-06-09, TODO: use a release instead
        with:
          artifact-name: "react-native-auth0"
          artifact-path: "${{ github.workspace }}/react-native-auth0.tgz"
          version: ${{ steps.get_version.outputs.version }}
          RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
          SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
          SIGNAL_HANDLER_DOMAIN: ${{ secrets.SIGNAL_HANDLER_DOMAIN }}
          PRODSEC_TOOLS_ARN: ${{ secrets.PRODSEC_TOOLS_ARN }}
          PRODSEC_TOOLS_USER: ${{ secrets.PRODSEC_TOOLS_USER }}
          PRODSEC_TOOLS_TOKEN: ${{ secrets.PRODSEC_TOOLS_TOKEN }}
          PRODSEC_PYTHON_TOOLS_REPO: ${{ secrets.PRODSEC_PYTHON_TOOLS_REPO }}

  release:
    uses: ./.github/workflows/npm-release.yml
    needs: rl-scanner
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-docs:
    needs: release
    if: success()
    uses: ./.github/workflows/publish-docs.yml
    permissions:
      contents: write
      pages: write
      id-token: write
