name: SCA

on:
  push:
    branches: ['master', 'main', '**']

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      node-version: '22'
      pre-scan-commands: |
        yarn install
        rm -f android/build.gradle
    secrets: inherit
